### ISSUE TITLE
Concurrency id support

### ISSUE THREAD

**Issue by therealthingy** [compudj/librseq#11]
Hi there,

I've 2 questions regarding `mm_cid`  (since the kernel 6.3.0 added support for the concurrency id):

  1. Are there currently plans to add also functionality (i.e., [`rseq_current_mm_cid`](https://github.com/torvalds/linux/blob/ae31573843028ad17b1a807081c542d17fa9a83a/tools/testing/selftests/rseq/rseq.h#L213)) for supporting this kernel feature in librseq?

  2. When I use the `mm_cid` to index into per-CPU data structures, do i need to check inside the critical section whether `mm_cid` matches (or just the `cpu_id` via `RSEQ_ASM_CMP_CPU_ID`)?

Thanks!

**Comment by compudj** [comment]
(1) yes I plan to integrate the mm_cid field support from the Linux kernel rseq selftests to librseq.

(2) If you use mm_cid to index your data structures, you need to check that the mm_cid matches in the critical section, cpu_id check is not enough, because even if you always run on a given cpu, there are scenarios where the mm_cid that can be observed may change.

**Comment by therealthingy** [comment]
Thanks for the clarification.

**Comment by compudj** [comment]
FYI, I have now merged the mm_cid support into librseq master.
